file:
  # 需要操作的文件的路径
  path: G:\电视剧

#  delete:
#    # 通过文件名删除文件,只要包括这些就行
#    names:
#      - "05"
#      - "06"
#
#    # 通过后缀来删除文件
#    suffixs:
#      - txt
#      - md
#      - png

  rename:
    # 改后的名字为原来名字匹配的字符组成的
    regex: (?<name>\d\d*).*?\.(?<suffix>.*)$
    # 已经修改成功的正则表达式
    success.regex: ^(?<name>\d\d*).*?\.(?<suffix>.*)$






